/**
 * File: app/terms-of-service/page.tsx
 * Version: v1.0
 * Purpose:
 * - Terms of Service page required for site protection and AdSense trust
 */

export default function TermsOfService() {
  return (
    <main
      style={{
        padding: "40px 20px",
        maxWidth: "900px",
        margin: "0 auto",
        color: "white",
        lineHeight: "1.6",
      }}
    >
      <h1 style={{ fontSize: "28px", fontWeight: "bold", marginBottom: "20px" }}>
        Terms of Service
      </h1>

      <p>
        By using this website ("Best Meeting Time"), you agree to the following terms.
      </p>

      <h2 style={{ marginTop: "20px" }}>Use of Service</h2>
      <p>
        This tool is provided for informational purposes only. You may use the service to find optimal meeting times across time zones.
      </p>

      <h2 style={{ marginTop: "20px" }}>No Guarantees</h2>
      <p>
        We do not guarantee the accuracy, reliability, or suitability of the results generated by this tool.
      </p>

      <h2 style={{ marginTop: "20px" }}>Limitation of Liability</h2>
      <p>
        We are not responsible for any decisions made based on the use of this tool. Use the service at your own discretion.
      </p>

      <h2 style={{ marginTop: "20px" }}>Changes to Terms</h2>
      <p>
        We reserve the right to update or modify these terms at any time without prior notice.
      </p>

      <p style={{ marginTop: "20px" }}>
        By continuing to use this site, you agree to these terms.
      </p>
    </main>
  );
}
