/**
 * File: app/terms-of-service/page.tsx
 * Version: v1.2
 * Purpose:
 * - Terms of Service page required for AdSense trust and legal protection
 * - Adds integrated site navigation and footer
 * - Prevents isolated legal-page UX
 *
 * Rollback:
 * - Revert to v1.1 if layout regression occurs
 */

import Link from "next/link";

export default function TermsOfService() {
  return (
    <main
      style={{
        minHeight: "100vh",
        background: "linear-gradient(180deg, #4c1d95 0%, #312e81 100%)",
        color: "white",
      }}
    >
      <nav
        style={{
          maxWidth: "1100px",
          margin: "0 auto",
          padding: "24px 20px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          gap: "20px",
          flexWrap: "wrap",
        }}
      >
        <Link
          href="/"
          style={{
            color: "white",
            fontWeight: 800,
            textDecoration: "none",
          }}
        >
          Best Meeting Time
        </Link>

        <div
          style={{
            display: "flex",
            gap: "18px",
            flexWrap: "wrap",
            alignItems: "center",
          }}
        >
          <Link href="/" style={{ color: "white", textDecoration: "none", fontWeight: 700 }}>
            Home
          </Link>

          <Link
            href="/how-it-works"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Schedule a Meeting
          </Link>

          <Link
            href="/features"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Features
          </Link>

          <Link
            href="/guides"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Guides
          </Link>

          <Link
            href="/blog"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Blog
          </Link>

          <Link
            href="/about"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            About
          </Link>

          <Link
            href="/contact"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Contact
          </Link>
        </div>
      </nav>

      <section
        style={{
          maxWidth: "900px",
          margin: "0 auto",
          padding: "40px 20px 70px",
          lineHeight: "1.6",
        }}
      >
        <h1
          style={{
            fontSize: "32px",
            fontWeight: "bold",
            marginBottom: "20px",
          }}
        >
          Terms of Service
        </h1>

        <p>
          By using this website ("Best Meeting Time"), you agree to the following terms.
        </p>

        <h2 style={{ marginTop: "24px" }}>Use of Service</h2>

        <p>
          This tool is provided for informational purposes only. You may use the
          service to find optimal meeting times across time zones.
        </p>

        <p>
          You agree not to misuse the service or attempt to disrupt its
          functionality, security, or availability.
        </p>

        <h2 style={{ marginTop: "24px" }}>No Guarantees</h2>

        <p>
          We do not guarantee the accuracy, reliability, or suitability of the
          results generated by this tool.
        </p>

        <h2 style={{ marginTop: "24px" }}>Service Availability</h2>

        <p>
          We do not guarantee that the service will be available at all times or
          free from interruptions or errors.
        </p>

        <h2 style={{ marginTop: "24px" }}>Limitation of Liability</h2>

        <p>
          We are not responsible for any decisions made based on the use of this
          tool. Use the service at your own discretion.
        </p>

        <h2 style={{ marginTop: "24px" }}>Changes to Terms</h2>

        <p>
          We reserve the right to update or modify these terms at any time
          without prior notice.
        </p>

        <p style={{ marginTop: "24px" }}>
          By continuing to use this site, you agree to these terms.
        </p>

        <p
          style={{
            marginTop: "30px",
            fontSize: "14px",
            opacity: 0.9,
          }}
        >
          If you have any questions about these Terms, you may contact us at:
          support@bestmeetingtimeapp.com
        </p>

        <div style={{ marginTop: "36px" }}>
          <Link
            href="/how-it-works"
            style={{
              display: "inline-block",
              background: "white",
              color: "#4c1d95",
              padding: "12px 18px",
              borderRadius: "12px",
              fontWeight: 800,
              textDecoration: "none",
            }}
          >
            Back to Schedule a Meeting
          </Link>
        </div>
      </section>

      <footer
        style={{
          borderTop: "1px solid rgba(255,255,255,0.2)",
          padding: "24px 20px 34px",
          textAlign: "center",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            gap: "22px",
            flexWrap: "wrap",
          }}
        >
          <Link href="/" style={{ color: "white", textDecoration: "none", fontWeight: 700 }}>
            Home
          </Link>

          <Link
            href="/guides"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Guides
          </Link>

          <Link
            href="/contact"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Contact
          </Link>

          <Link
            href="/privacy-policy"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Privacy Policy
          </Link>

          <Link
            href="/terms-of-service"
            style={{ color: "white", textDecoration: "none", fontWeight: 700 }}
          >
            Terms of Service
          </Link>
        </div>
      </footer>
    </main>
  );
}
